# Generated by Django 6.0.3 on 2026-04-06 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_alter_hobby_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_hobbies', to=settings.AUTH_USER_MODEL),
        ),
    ]
